# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exception.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "PuppetRubyHost.Protocols.Exception" do
    optional :message, :string, 1
    optional :context, :message, 2, "PuppetRubyHost.Protocols.Exception.SourceContext"
    repeated :backtrace, :message, 3, "PuppetRubyHost.Protocols.Exception.StackFrame"
  end
  add_message "PuppetRubyHost.Protocols.Exception.SourceContext" do
    optional :file, :string, 1
    optional :begin, :message, 2, "PuppetRubyHost.Protocols.Exception.SourceContext.Position"
    optional :end, :message, 3, "PuppetRubyHost.Protocols.Exception.SourceContext.Position"
  end
  add_message "PuppetRubyHost.Protocols.Exception.SourceContext.Position" do
    optional :line, :int64, 1
    optional :offset, :int64, 2
  end
  add_message "PuppetRubyHost.Protocols.Exception.StackFrame" do
    optional :name, :string, 1
    optional :file, :string, 2
    optional :line, :int64, 3
  end
end

module PuppetRubyHost
  module Protocols
    Exception = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.Exception").msgclass
    Exception::SourceContext = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.Exception.SourceContext").msgclass
    Exception::SourceContext::Position = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.Exception.SourceContext.Position").msgclass
    Exception::StackFrame = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.Exception.StackFrame").msgclass
  end
end
