# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: function.proto

require 'google/protobuf'

require_relative 'value'
require_relative 'exception'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "PuppetRubyHost.Protocols.DescribeFunctionRequest" do
    optional :environment, :string, 1
    optional :name, :string, 2
  end
  add_message "PuppetRubyHost.Protocols.DescribeFunctionResponse" do
    oneof :kind do
      optional :function, :message, 1, "PuppetRubyHost.Protocols.DescribeFunctionResponse.Function"
      optional :exception, :message, 2, "PuppetRubyHost.Protocols.Exception"
    end
  end
  add_message "PuppetRubyHost.Protocols.DescribeFunctionResponse.Function" do
    optional :name, :string, 1
    optional :file, :string, 2
    optional :line, :int64, 3
    repeated :dispatches, :message, 4, "PuppetRubyHost.Protocols.DescribeFunctionResponse.Function.Dispatch"
  end
  add_message "PuppetRubyHost.Protocols.DescribeFunctionResponse.Function.Dispatch" do
    optional :id, :string, 1
    optional :name, :string, 2
    repeated :types, :string, 3
    repeated :names, :string, 4
    optional :min, :int64, 5
    optional :max, :int64, 6
    optional :block_type, :string, 7
    optional :block_name, :string, 8
  end
  add_message "PuppetRubyHost.Protocols.InvokeFunctionRequest" do
    oneof :kind do
      optional :call, :message, 1, "PuppetRubyHost.Protocols.InvokeFunctionRequest.Call"
      optional :continuation, :message, 2, "PuppetRubyHost.Protocols.InvokeFunctionRequest.Continuation"
    end
  end
  add_message "PuppetRubyHost.Protocols.InvokeFunctionRequest.Call" do
    optional :environment, :string, 1
    optional :id, :string, 2
    repeated :arguments, :message, 3, "PuppetRubyHost.Protocols.Value"
    optional :has_block, :bool, 4
  end
  add_message "PuppetRubyHost.Protocols.InvokeFunctionRequest.Continuation" do
    oneof :kind do
      optional :result, :message, 1, "PuppetRubyHost.Protocols.Value"
      optional :exception, :message, 2, "PuppetRubyHost.Protocols.Exception"
    end
  end
  add_message "PuppetRubyHost.Protocols.InvokeFunctionResponse" do
    oneof :kind do
      optional :result, :message, 1, "PuppetRubyHost.Protocols.Value"
      optional :yield, :message, 2, "PuppetRubyHost.Protocols.InvokeFunctionResponse.Yield"
      optional :exception, :message, 3, "PuppetRubyHost.Protocols.Exception"
    end
  end
  add_message "PuppetRubyHost.Protocols.InvokeFunctionResponse.Yield" do
    repeated :arguments, :message, 1, "PuppetRubyHost.Protocols.Value"
  end
end

module PuppetRubyHost
  module Protocols
    DescribeFunctionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.DescribeFunctionRequest").msgclass
    DescribeFunctionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.DescribeFunctionResponse").msgclass
    DescribeFunctionResponse::Function = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.DescribeFunctionResponse.Function").msgclass
    DescribeFunctionResponse::Function::Dispatch = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.DescribeFunctionResponse.Function.Dispatch").msgclass
    InvokeFunctionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.InvokeFunctionRequest").msgclass
    InvokeFunctionRequest::Call = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.InvokeFunctionRequest.Call").msgclass
    InvokeFunctionRequest::Continuation = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.InvokeFunctionRequest.Continuation").msgclass
    InvokeFunctionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.InvokeFunctionResponse").msgclass
    InvokeFunctionResponse::Yield = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.InvokeFunctionResponse.Yield").msgclass
  end
end
