# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: type.proto for package 'PuppetRubyHost.Protocols'

require 'grpc'
require_relative 'type'

module PuppetRubyHost
  module Protocols
    module Type
      # The Puppet resource type service.
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'PuppetRubyHost.Protocols.Type'

        # Describes a Puppet resource type.
        rpc :Describe, DescribeTypeRequest, DescribeTypeResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
