# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: value.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "PuppetRubyHost.Protocols.Value" do
    oneof :kind do
      optional :symbol, :enum, 1, "PuppetRubyHost.Protocols.Value.Symbol"
      optional :integer, :int64, 2
      optional :float, :double, 3
      optional :boolean, :bool, 4
      optional :string, :string, 5
      optional :regexp, :string, 6
      optional :type, :string, 7
      optional :array, :message, 8, "PuppetRubyHost.Protocols.Value.Array"
      optional :hash, :message, 9, "PuppetRubyHost.Protocols.Value.Hash"
    end
  end
  add_message "PuppetRubyHost.Protocols.Value.Array" do
    repeated :elements, :message, 1, "PuppetRubyHost.Protocols.Value"
  end
  add_message "PuppetRubyHost.Protocols.Value.Hash" do
    repeated :elements, :message, 1, "PuppetRubyHost.Protocols.Value.Hash.KeyValuePair"
  end
  add_message "PuppetRubyHost.Protocols.Value.Hash.KeyValuePair" do
    optional :key, :message, 1, "PuppetRubyHost.Protocols.Value"
    optional :value, :message, 2, "PuppetRubyHost.Protocols.Value"
  end
  add_enum "PuppetRubyHost.Protocols.Value.Symbol" do
    value :UNDEF, 0
    value :DEFAULT, 1
  end
end

module PuppetRubyHost
  module Protocols
    Value = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.Value").msgclass
    Value::Array = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.Value.Array").msgclass
    Value::Hash = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.Value.Hash").msgclass
    Value::Hash::KeyValuePair = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.Value.Hash.KeyValuePair").msgclass
    Value::Symbol = Google::Protobuf::DescriptorPool.generated_pool.lookup("PuppetRubyHost.Protocols.Value.Symbol").enummodule
  end
end
